# Generated by Django 3.0.1 on 2019-12-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='body',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='title',
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
