# Generated by Django 3.0.1 on 2019-12-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20191227_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='presence',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
