# Generated by Django 3.0.1 on 2019-12-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20191227_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='basic_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mapr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(max_length=12)),
                ('presence', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
