# Generated by Django 3.0.1 on 2019-12-28 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20191227_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapr',
            name='bi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='students.basic_info'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapr',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
