# Generated by Django 3.0.1 on 2019-12-28 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20191228_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapr',
            name='bi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.basic_info'),
        ),
    ]
