# Generated by Django 3.0.1 on 2019-12-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20191228_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_info',
            name='marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basic_info',
            name='presence',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='mapr',
        ),
    ]
