# Generated by Django 3.0.1 on 2019-12-28 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20191228_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_info',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='basic_info',
            name='presence',
        ),
        migrations.CreateModel(
            name='mapr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('presence', models.BooleanField()),
                ('bi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.basic_info')),
            ],
        ),
    ]
